# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf118a7760fc2ea69ce61aedbe4d1325139e29d42d432a0c96f6d87c710413d109cdb3d1e9f89ae8f307f16a15995a58e5bb459ef9c303d1f54a6f2d3b50946

test:
  secret_key_base: ed993943c5dd8d591f6eeb1aa41b08e04f858e15156687686f30ca70ede35698bcd0926c069ddb9b51b8bf00b84745af5938680410389cf102727b2658a47aaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
